import RPi.GPIO as GPIO
from time import sleep

def update_bottone_function(pin):
    print(pin)
    
GPIO.setmode(GPIO.BCM)

GPIO.setup(14,GPIO.IN)
GPIO.add_event_detect(14,GPIO.FALLING)
GPIO.add_event_callback(14, update_bottone_function)
GPIO.setup(15,GPIO.IN)
GPIO.add_event_detect(15,GPIO.FALLING)
GPIO.add_event_callback(15, update_bottone_function)
GPIO.setup(18,GPIO.IN)
GPIO.add_event_detect(18,GPIO.FALLING)
GPIO.add_event_callback(18, update_bottone_function)
GPIO.setup(23,GPIO.IN)
GPIO.add_event_detect(23,GPIO.FALLING)
GPIO.add_event_callback(23, update_bottone_function)
GPIO.setup(17,GPIO.IN)
GPIO.add_event_detect(17,GPIO.FALLING)
GPIO.add_event_callback(17, update_bottone_function)
GPIO.setup(27,GPIO.IN)
GPIO.add_event_detect(27,GPIO.FALLING)
GPIO.add_event_callback(27, update_bottone_function)
GPIO.setup(22,GPIO.IN)
GPIO.add_event_detect(22,GPIO.FALLING)
GPIO.add_event_callback(22, update_bottone_function)
GPIO.setup(6,GPIO.IN)
GPIO.add_event_detect(6,GPIO.FALLING)
GPIO.add_event_callback(6, update_bottone_function)
GPIO.setup(13,GPIO.IN)
GPIO.add_event_detect(13,GPIO.FALLING)
GPIO.add_event_callback(13, update_bottone_function)
GPIO.setup(19,GPIO.IN)
GPIO.add_event_detect(19,GPIO.FALLING)
GPIO.add_event_callback(19, update_bottone_function)
GPIO.setup(26,GPIO.IN)
GPIO.add_event_detect(26,GPIO.FALLING)
GPIO.add_event_callback(26, update_bottone_function)
GPIO.setup(12,GPIO.IN)
GPIO.add_event_detect(12,GPIO.FALLING)
GPIO.add_event_callback(12, update_bottone_function)
GPIO.setup(16,GPIO.IN)
GPIO.add_event_detect(16,GPIO.FALLING)
GPIO.add_event_callback(16, update_bottone_function)
GPIO.setup(20,GPIO.IN)
GPIO.add_event_detect(20,GPIO.FALLING)
GPIO.add_event_callback(20, update_bottone_function)
GPIO.setup(21,GPIO.IN)
GPIO.add_event_detect(21,GPIO.FALLING)
GPIO.add_event_callback(21, update_bottone_function)

while True:
    sleep(1)
