# Generated by Django 2.0.3 on 2018-04-01 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=14)),
                ('path', models.CharField(default=None, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('testo', models.CharField(max_length=8000)),
                ('date', models.DateTimeField()),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aTelegram.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(default=None, max_length=14)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aTelegram.Session'),
        ),
    ]
