# Generated by Django 2.0.3 on 2018-05-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aTelegram', '0003_auto_20180524_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='cont_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='from_id', to='aTelegram.Contact'),
        ),
        migrations.AddField(
            model_name='message',
            name='out',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='num',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='contact',
            name='num_bottone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
