# Generated by Django 2.0.3 on 2018-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aTelegram', '0004_auto_20180528_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='path',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
