# Generated by Django 2.0.3 on 2018-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aTelegram', '0005_message_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='num',
            field=models.CharField(default='', max_length=14, null=True),
        ),
    ]
